### ISSUE TITLE
options not read from config file

### ISSUE THREAD

**Issue by vsoch** [LLNL/shroud#221]
Hi shroud team!

I was using shroud just now, and expecting this config to generate Python output:

```yaml
library: abispack
namespace: abispack
cxx_header: include/abispack.h

options:
  wrap_fortran: False
  wrap_c: False
  wrap_python: True
  debug: True

declarations:
- decl: class Libabigail
  declarations:
  - decl: Libabigail()
  - decl: void GetVersion()
```
The problem is that it didn't - it only made a .f (fortran I think?) file!

```bash
# cat abispack.log 
Close wraplibrary.cpp
Close typeslibrary.h
Close wrapflibrary.f
```
I inspected the client to see that I could add an `--option` and this seemed to work!

```bash
# shroud --option wrap_python=True --option wrap_fortran=False --option wrap_c=False --option debug=True abispack.yml 
Wrote pylibrarymodule.cpp
Wrote pylibrarymodule.hpp
Wrote setup.py
```
But I'd really like to be able to have these options in my yaml configuration file and just run `shroud abigail.yml`. Thanks for your help!
