### ISSUE TITLE
template struct

### ISSUE THREAD

**Issue by wojdyr** [LLNL/shroud#232]
I'm just starting using shroud.  I tried to wrap a templated struct.

First, with class template it works as expected, for example
```yaml
library: abc
declarations:
- decl: template<typename T> class Abc
  cxx_template:
    - instantiation: <float>
```

but if I try to use struct instead of class:
```yaml
library: abc
options:
  wrap_struct_as: class
declarations:
- decl: template<typename T> struct Abc
  cxx_template:
    - instantiation: <float>
```

shroud gives error (regardless of what wrap_struct_as is set to):
```
RuntimeError: Parse Error
template<typename T> struct Abc
                     ^
Expected TYPE_SPECIFIER, found STRUCT 'struct'
```
Is there a workaround?

Thanks for this project, it will save me a lot of work.
