### ISSUE TITLE
adding header files to wrapNAME.cpp

### ISSUE THREAD

**Issue by wojdyr** [LLNL/shroud#235]
With this config:
```yaml
library: abc
namespace: abc
#cxx_header: a.hpp

declarations:

- decl: class A
  cxx_header: a.hpp
  declarations:
  - decl: A()

- decl: class B
  cxx_header: b.hpp
  declarations:
  - decl: B()
```

wrapA.cpp has `#include "a.hpp"` and wrapB.cpp has `#include "b.hpp"`.
wrapabc.cpp which uses both abc::A and abc::B in `ABC_SHROUD_memory_destructor` doesn't have these includes. I could specify global cxx_header, but can I add more than one header there? Ideally, these headers would be included automatically.
