### ISSUE TITLE
A<int> as a return value

### ISSUE THREAD

**Issue by wojdyr** [LLNL/shroud#238]
I have a function that returns a templated class, such as `A<int> func2()`.
Here is an example configuration:

```yaml
library: abc
namespace: abc

declarations:

- decl: template<typename T> class A
  cxx_template:
    - instantiation: <int>
  declarations:
  - decl: A()
- decl: vector<int> func1()
- decl: A<int> func2()
```

In a few places in the generated code the type is ignored and instead of `A<int>` or `A_int` we get just `A` (it works correctly for `vector<int>`, though).
For example, in `wrapabc.cpp` I get destructors for both `A<int>` and `A` (the latter won't compile of course):

```cpp
// Release library allocated memory.
void ABC_SHROUD_memory_destructor(ABC_SHROUD_capsule_data *cap)
{
    void *ptr = cap->addr;
    switch (cap->idtor) {
    case 0:   // --none--
    {
        // Nothing to delete
        break;
    }
    case 1:   // abc::A<int>
    {
        abc::A<int> *cxx_ptr = reinterpret_cast<abc::A<int> *>(ptr);
        delete cxx_ptr;
        break;
    }
    case 2:   // std_vector_int
    {
        std::vector<int> *cxx_ptr = reinterpret_cast<std::vector<int> *>(ptr);
        delete cxx_ptr;
        break;
    }
    case 3:   // abc::A
    {
        abc::A *cxx_ptr = reinterpret_cast<abc::A *>(ptr);
        delete cxx_ptr;
        break;
    }
    default:
    {
        // Unexpected case in destructor
        break;
    }
    }
    cap->addr = nullptr;
    cap->idtor = 0;  // avoid deleting again
}
```
