### ISSUE TITLE
string member variable: Error with template

### ISSUE THREAD

**Issue by wojdyr** [LLNL/shroud#240]
If I try to declare member variable of type string:

```yaml
library: abc
namespace: abc
cxx_header: abc.hpp

declarations:
- decl: class A
  declarations:
  - decl: string x;
```

I get:

    Error with template: '{cxx_var}{cxx_member}c_str()'
