### ISSUE TITLE
splicer as YAML multiline text

### ISSUE THREAD

**Issue by wojdyr** [LLNL/shroud#243]
A feature request.
Splicer code in a list works fine:

```yaml
splicer_code:
  c:
    CXX_definitions:
      - '// aaa'
      - '// bbb'
```

It's not super important, but in some cases it'd be slightly more convenient to have it as multiline text.
If I try this:

```
splicer_code:
  c:
    CXX_definitions: |
      // aaa
      // bbb
```

I get one character per line

```
// splicer begin CXX_definitions
/
/
 
a
a
a
...
```
