### ISSUE TITLE
Add interface wrapper for functions with default arguments defined as class members

### ISSUE THREAD

**Issue by CarvFS** [LLNL/shroud#315]
Hello!

I have noticed one thing while defining member functions of a class containing default arguments. 

If the Shroud script is just for the function, e.g.:

```
library: Tutorial
format:
  F_filename_suffix: F90
cxx_header: tutorial.hpp

declarations:
- decl: int Method1(int arg1)
- decl: int Method2(int arg1, int arg2 = 1, double arg3 = 0.5)
```

The Fortran wraper will have an interface wraper defined as:

```
    interface method2
        module procedure method2_0
        module procedure method2_1
        module procedure method2_2
    end interface method2
```

Thus, one may use the function as, for example, `value = method2(arg1,optional_args)`.

However, if the functions is defined as class member, e.g.:

```
library: Tutorial
format:
  F_filename_suffix: F90
cxx_header: tutorial.hpp

- decl: namespace tutorial
  declarations:
  - decl: class Class1
    declarations:
    - decl: Class1(int arg1, int arg2 = 1, double arg3 = 0.5) +name(new)
    - decl: ~Class1() +name(delete)
    - decl: int Method1(int arg1)
    - decl: int Method2(int arg1, int arg2 = 1, double arg3 = 0.5)
```

The Fortran wrapper contains only the interface for the constructor:

```
    interface class1
        module procedure class1_new_0
        module procedure class1_new_1
        module procedure class1_new_2
    end interface class1
```

And the functions are defined as procedures inside the defined type:

```
        procedure :: method1 => class1_method1
        procedure :: method2_0 => class1_method2_0
        procedure :: method2_1 => class1_method2_1
        procedure :: method2_2 => class1_method2_2
        [...]
        generic :: method1 => method1_0, method1_1, method1_2
        generic :: method2 => method2_0, method2_1, method2_2
```

Thus one may use the functions in the main Fortran program as type-bound functions:

```
cptr = Class1(1, 2, 0.1) 

value1 = cptr%method1(1)
value2 = cptr%method2(1, optional_args)
```

In this case, `method1` can also be used as `class1_method1(cptr, 1)`. However this is not possible for `method2`. I have managed to solve this by manually adding the interface for `method2`: 

```
    interface class1_method2
        module procedure method2_0
        module procedure method2_1
        module procedure method2_2
    end interface class1_method2
```

However, if one needs to run shroud again it will be needed to keep inserting the interface into the fortran wrapper. It seems there is no splicer to keep this additions in the `splicer.f` file.

Is there some shroud input I am missing for this case?

Thank you very much!
Felipe Silva Carvalho
